baseURL = 'http://www.jukie.net/~bart/'
languageCode = 'en-us'
title = "bartman's blog"
#theme = 'terminal'
theme = 'hugo-theme-re-terminal'

[markup.goldmark.renderer]
  unsafe= true

[params]
  contentTypeName = "blog"
  themeColor = "orange"
  showMenuItems = 10
  showLanguageSelector = false
#showLastUpdated = true
  enableGitInfo = true           # use git for last update
  autoCover = true
  fullWidthTheme = false
  centerTheme = true
  readingTime = true
# [params.banner]
#   dismissible = false
#   text = "bartman's blog"
#   url = "https://github.com/bartman"

[params.twitter]
  creator = "bart.trojanowski"
  site = ""

[languages]
  [languages.en.params]
    languageName = "English"
    title = "bartman's blog"
    subtitle = ""
    owner = ""
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"


    [languages.en.params.logo]
      logoText = "bartman's blog"
      logoHomeLink = "/~bart/"

[languages.en.menu]
# [[languages.en.menu.main]]
#   identifier = "submenu"
#   name = "Sub menus"
#   weight = 10
# [[languages.en.menu.main]]
#   identifier = "subabout"
#   name = "About"
#   url = "/about"
#   parent = "submenu"
# [[languages.en.menu.main]]
#   identifier = "subshowcase"
#   name = "Showcase"
#   url = "/showcase"
#   parent = "submenu"
  [[languages.en.menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/"
  [[languages.en.menu.main]]
    identifier = "consulting"
    name = "consulting"
    url = "/consulting"
  [[languages.en.menu.main]]
    identifier = "resume"
    name = "resume"
    url = "/resume"
  [[languages.en.menu.main]]
    identifier = "sig"
    name = "sig"
    url = "/sig"

  [[languages.en.menu.main]]
    identifier = "tags"
    name = "tags"
    url = "/tags"

